#服务端口
server:
  port: 9001
#服务别名，注册到注册中心的服务别名
spring:
  application:
    name: yinzhh-member-zk
  cloud:
    zookeeper:
      # zookeeper注册中心地址，默认localhost:2181
      connect-string: 47.106.137.210:2181


